### ISSUE TITLE
[Ant build.xml] Add Ant Ivy for dependency resolving

### ISSUE THREAD

**Issue by verhagen** [Progether/JAdventure#157]
__For development__ a project should never contain the libraries it depends on, but use Ivy, for downloading them.
__Packaging__ When the application gets packaged (making it ready for end users), the classes should go in their own jar. And a zip (or installer) should be created, which includes the JAdventure.jar and all it dependencies (downloaded through Ivy).
The zip / installer can then be pushed on a web-page for downloading.
Creating a Java installer can be done with [Lift Off](http://liftoff.sourceforge.net/)

**Comment by paddatrapper** [comment]
Fixed in pull request #215
