### ISSUE TITLE
Split Item ID, it should not contain hidden information

### ISSUE THREAD

**Issue by verhagen** [Progether/JAdventure#162]
The Item ID is not only an ID, but contains Item meta information.
Apply separation of concern for the field ID. Create extra fields in Item:
- String **type** (already there) 
- Integer **level** _that is the last number in the (current) ID_

This way the ID is just an Identity reference. More clear, when no additional information is encoded in it.

**Comment by paddatrapper** [comment]
Can this be closed? Seems like it is a no-fix issue

**Comment by verhagen** [comment]
__Keep the field *id* as is__
Never have double information in your class or json, so remove the level and type field from the class. And extra the data from the ID field. So keep the methods: getType() and getLevel(), but let it extract that data from the field ID. And do not store the *type* and *level* as separate values in json files.

__Keep the fields *type* and *level* as is__
Make the ID clean, so do not pseudo code the type and level in the field *id*.

**Comment by paddatrapper** [comment]
If we strip info out of it how then do we create an ID so that it is human readable/logical and unique?

**Comment by Dev-Osmium** [comment]
I agree with projectdelphai. The IDs are perfectly fine, and if people want to look at them, they sure as hell can.

**Comment by verhagen** [comment]
Just leave it as is.
