### ISSUE TITLE
Create a test linux installation

### ISSUE THREAD

**Issue by projectdelphai** [Progether/JAdventure#203]
We should try to at least have a basic package that can be sent to a person so they can try out the game without any problems. I'm proposing a linux one to start out with (since that's what I use) but we'll eventually need to branch out. An ideal package would be a simple jar file. 
1. Single jar file
2. It downloads the dependencies if they don't exist already
3. sets up the profiles folder and copies the necessary original_data files
4. starts the server or client

Someone who doesn't program should be able to start playing this game just by running the jar file. This NEEDS to be done for linux (and then windows and osx) to get good data back from an alpha version.

**Comment by paddatrapper** [comment]
@verhagen suggested we use Ivy for the dependency downloading - #157. I'll see if that would help here or not.

**Comment by projectdelphai** [comment]
Ivy dependencies would work well for ant-based stuff for developers. However for end-users who just want to play the game, they should be using a standard linux package so ant might not be the best solution for that. In standard packages, binaries are in /usr/bin etc.

**Comment by paddatrapper** [comment]
Yeah. I've been working with ivy at the moment (pull request coming now) and I've realised it won't help.

**Comment by paddatrapper** [comment]
Also the JAdventure jar looks for libs in the same directory as it is in so we need to keep that in mind when packaging

**Comment by verhagen** [comment]
No the JVM looks for jars on the classpath. So if you create a lib
directory in the JAdventure packaged directory, and also add the JAdventure
own jar there, then you just need the add that lib dorectory to the
classpath and all jars, from there will be used as through the class loader
if it requires a class from a jar.

**Comment by paddatrapper** [comment]
#244 creates a .tar.gz, .tar.bx2 and a .zip that can be used for distribution, which solves this issue. I would prefer not to manage Debian/Ubuntu, arch, etc packages when this is at such a early point in development, as supporting a static version of quickly changing application for 5 years is a large commitment.
