### ISSUE TITLE
Equipping broadsword does not add it to equipment list

### ISSUE THREAD

**Issue by paddatrapper** [Progether/JAdventure#212]
With shiv equipped trying to equip a broadsword adds the damage buff from the broadsword, however it does not unequip the shiv or remove the damage buff gained from the shiv. `ve` returns that the shiv is equipped and not the broadsword.

I suspect this is because the broadsword is two handed and thus breaking the equip logic.

**Comment by projectdelphai** [comment]
You also cannot unequip the broadsword and replace it with another weapon or shield. Probably for the same problems.
