### ISSUE TITLE
bug with equipping armour

### ISSUE THREAD

**Issue by projectdelphai** [Progether/JAdventure#216]
when equipping armour, a lot of items aren't being registered properly. it doesn't show up as equipped and items are constantly disappearing and appearing in my backpack. may be related to #214

**Comment by paddatrapper** [comment]
I've sorted this, was somewhat related, but not as closely as I expected. https://github.com/paddatrapper/JAdventure/tree/equip-armour

I'll place the pull request once #214 is finalised, as it makes use of that code base.

**Comment by projectdelphai** [comment]
ready for this pull request.
