### ISSUE TITLE
Talking to Syndicate member causes null point exception

### ISSUE THREAD

**Issue by The-Host** [Progether/JAdventure#220]
Talked to the guide just fine; appears to just be Syndicate member at the moment. Here's a paste bin of the error.
http://pastebin.com/FHjhJ8FH

**Comment by paddatrapper** [comment]
I'm pretty sure this is because the json condition is not matching an enumerated ConditionType

**Comment by paddatrapper** [comment]
Fixed in commit 8f1d392
