### ISSUE TITLE
Creating new profiles deletes equipped armors in all other profiles

### ISSUE THREAD

**Issue by The-Host** [Progether/JAdventure#223]
Creating a new profile at any point deletes all armor in all other profiles. Equipped weapons don't change, but all armor is completely removed while the armor rating stays the same, Because of this, you can stack your armor rating by putting on armor and making new profiles. I was able to get a rating well above 50 through testing the bug.

**Comment by paddatrapper** [comment]
This is because equipped items are not saved to the profile. The only reason the weapon is saved is because the weapon property of the Entity class is saved. So to fix equipped items need to be saved and loaded with EquipmentLocation positions

**Comment by paddatrapper** [comment]
Commit 2b128cbff11e082b6764ced834bd96d322c70f1d fixes this by save equipment to profile and loading it.
