### ISSUE TITLE
Saving after killing an NPC on one profile saves NPC death on all profiles

### ISSUE THREAD

**Issue by The-Host** [Progether/JAdventure#224]
Saving after killing an NPC on "A" profile and then switching over to "B" profile carries over the items and dead NPC's of the "A" profile. There is no way to get back what was originally on "B" profile and creating a new profile also gains the items and dead NPC's of profile "A". The only way to get NPC's back is by creating a new profile right after executing the program and then saving the game. After that, all profiles will have the starting locations along with the living NPC's.

**Comment by paddatrapper** [comment]
fixed in commit 26dbbde65ae15aadbc019dc5d6cc157950da9548. Unfortunately not as exciting as I though it would be. The issue was that when loading a profile the locations stored by the LocationManager were not reloaded to reflect the new profile
