### ISSUE TITLE
Items should cost more when you sell them to the npc

### ISSUE THREAD

**Issue by projectdelphai** [Progether/JAdventure#225]
I've been trying to remember this issue forever but I finally remember with the latest closed issue:

NPCs should charge more for items after the player sells them to the NPC. This creates a level of hardness for the player so they have to weigh the pros/cons of selling to the npc. It also makes sense in the game because npcs want to gain a profit.

**Comment by paddatrapper** [comment]
This can also include specific trading tendencies. So weapon trades markup non-weapons much more than weapons for example. This makes the player move around so as to try get the better deal for the items he wants.

**Comment by projectdelphai** [comment]
That's a great idea! We could base it based on their item trading preference so we don't have to add another property.

**Comment by indivisible-irl** [comment]
You could also take location into account. Different places would have different resources available locally and demands would be different in different areas (or economies).

e.g. An NPC in a farming village would charge or pay a tiny amount for farming gear whereas one in a mountainous area might either buy/sell at a higher price or perhaps not even want to buy the item as it is not useful for their locale.

Just a thought.

**Comment by projectdelphai** [comment]
#234 solves this
