### ISSUE TITLE
Merge json/ and json/original_data

### ISSUE THREAD

**Issue by paddatrapper** [Progether/JAdventure#226]
There seems to be a lot of duplication of files between json/original_data and json/. For example locations exists in both. Why are there 2 copies of the file, while neither one should be edited by the game (as this is done from within the profile folder)? I propose all files that should not be changed as well as the unmodified versions of changeable files be kept in original_data. Files are then copied into profiles as needed and manipulated there. This would leave the base json/ empty.

**Comment by Dev-Osmium** [comment]
This sounds like a good idea. Will implement on my branch and test
