### ISSUE TITLE
Conversation menu infinite loop

### ISSUE THREAD

**Issue by paddatrapper** [Progether/JAdventure#230]
Talk to guide. Select buy from guide. Press enter without selecting an item to buy. The menu goes back to the buy/sell choice, but does not read input from the user

**Comment by PeterWathall** [comment]
The exit option doesn't appear to be working for me at all, even with a fresh world. I'm going to try and look into it

**Comment by paddatrapper** [comment]
What do you mean by exit not working? Can you describe the steps to reproduce the issue?

**Comment by Jeschli** [comment]
Can't reproduce it.

**Comment by paddatrapper** [comment]
I'll try again tomorrow. Unfortunately no power at the moment so I can't
check it now

**Comment by paddatrapper** [comment]
I can't either... Closing this as won't fix
