### ISSUE TITLE
Standalone jar doesn't recognize external libraries

### ISSUE THREAD

**Issue by projectdelphai** [Progether/JAdventure#236]
Platform: Windows 10

The current standalone jar created doesn't run since it can't find the external library jar files we use. If you extract the lib folder and place it at the root directory then you can run:

    java -jar JAdventure.jar 

and it'll work fine but not until then. Working on fixing it now.

**Comment by paddatrapper** [comment]
There is an option in maven to build the dependencies directly into the jar archive. So I'm sure there must be a way to do it in ant as well. I'll take a look today and see what I can find

**Comment by projectdelphai** [comment]
I saw a way with one-jar but it's on sourceforge and the more i work with it the less i like it so hopefully there's a way to do it in ant directly that works

**Comment by paddatrapper** [comment]
If you are able to use maven dependencies in ant: maven-assembly-plugin

**Comment by projectdelphai** [comment]
9ca13f fixed this. You have two options once you run `ant dist`, it creates a JAdventure.jar which requires the lib and json folder found in "build" or you can use the JAdventure-single.jar which only requires the json folder. I'll work on integrating the json folder and using relative paths another time but this solves needing less folders on start and transferring.
