### ISSUE TITLE
i lost my file 

### ISSUE THREAD

**Issue by Timeriovo** [Progether/JAdventure#238]
![image](https://user-images.githubusercontent.com/29894156/32875474-1cda91c2-cad3-11e7-8805-d3c100b22516.png)
- I don't know how to walk and what to do
- I don't know why user doesn't exist

**Comment by paddatrapper** [comment]
Selecting a profile requires entering the name. It should probably be changed to allow entering the number too.

To walk: `go north` (or whatever direction)

It has been a while since I last played, but I think there is a `help` command that should give you the other commands

**Comment by Timeriovo** [comment]
thank you~Um...it's a great game

**Comment by Dev-Osmium** [comment]
This needs to be closed
